### PR TITLE
feat(vm): fix adding/removing hostpci devices forcing vm recreation

### LINKED ISSUE #503: Adding/removing hostpci devices forces vm recreation
When adding or removing a hostpci argument to a vm resource, the vm is forced to be recreated. This should not happen, since adding/removing hostpci devices via the ui is possible. Although, it seems that a reboot would be required.

**To Reproduce**
1. Create a resource vm without a hostpci device
2. Run `terraform apply` 
3. VM is created correctly with the device attached
4. Modify the resource, remove the hostpci device
5. Run `terraform apply` 
6. See the vm being recreated

The same can be witnessed, when creating a vm with a hostpci device and then later remove it.

The following resource can be used in order to reproduce the issue:
```terraform
resource "proxmox_virtual_environment_vm" "recreate_when_hostpci_changes" {
  name        = "recreate-when-hostpci-changes"
  description = "## TEST recreate-when-hostpci-changes"

  node_name = "foo"

  started = false

  cpu {
    cores = 1
  }

  memory {
    dedicated = 512
  }

  operating_system {
    type = "l26"
  }

  network_device {
    bridge = "vmbr0"
  }

  hostpci {
    device = "hostpci0"
    id = "81:00.8"
    rombar = true
  }
}
```

**Expected behavior**
Adding/removing hostpci devices to/from a vm should not force recreation of the vm.

**Additional context**
Provider version: Tested with 0.29.0 but the problem was present since the introduction of the hostpci argument
Terraform version: v1.5.1
OS: Running from wsl on Windows 10

I'll be trying to come up with a pull request.

### PR DESCRIPTION
**Pull request by michaelze**
### Contributor's Note
Please mark the following items with an [x] if they apply to your PR.
Leave the [ ] if they are not applicable, or if you have not completed the item.
- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/examples` for any new or updated resources / data sources.
- [x] I have ran `make examples` to verify that the change works as expected. 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #503

### CODE REVIEW

**Comment by michaelze** [comment]
@bpg I'm trying to work on this. Changing the `ForceNew` property of the hostpci schema seems to allow to add new hostpci devices and also update existing ones without the vm being recreated.

Removing hostpci devices on the other hand does not work as expected:
- `terraform plan` indicates the hostpci device being deleted
- running `terraform apply` however succeeds but neither the hostpci device is removed from the vm nor is the state updated
- subsequent `terraform plan` shows the same plan as before.

As I'm not famliar with the code base would you mind giving me some pointers where to start analyzing?
Thanks!

**Comment by bpg** [comment]
Thanks for taking care of this @michaelze! I'll take a look on the weekend and get back to you.

Will try to merge all the opened PRs and have a solid release 🙂

**Review by bpg — APPROVED** [review]
Okay, I know where is the problem with delete -- PVE API requires deleted devices to be explicitly listed in `delete` attribute of the update body. This piece was missing for `hostpci` as you know... they were not meant to be updated without the VM destroy 😅

So I've took a liberty to [add it](https://github.com/bpg/terraform-provider-proxmox/pull/504/files#diff-12bcc7e08b8cbd66ab84826d19fa7875cc1ce8acda247d75e508a3835ace5c15R5305-R5307) to your PR.
I've also [fixed](https://github.com/bpg/terraform-provider-proxmox/pull/504/files#diff-2f1b4764b499dad0e71c1d1ec4643ab8ecb1b91e24e00c6e4bbe3ecd9c242a89R1625) a separate bug with device IDs that was introduced in #500.
So I'm just going to merge this PR. 

Thanks for contributing @michaelze!

**Comment by bpg** [comment]
@all-contributors please add @michaelze for bug

**Comment by michaelze** [comment]
@bpg Now that is some good news to have in your inbox on a monday morning :smile:!
Thanks for the fix and I already tried out 0.30.0 and it works perfectly!

**Pull request merged**
