### PR TITLE
fix: snippets upload

### LINKED ISSUE #1011: Error: error moving file: rm: cannot remove
When trying to create a file using `proxmox_virtual_environment_file` we got an error:

```terraform
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.proxmox_node_name
  overwrite    = true

  source_file {
    path      = "cloudinit.yaml"
    file_name = "debian12.cloud-config.yaml"
  }
}
```

Error: error moving file: rm: cannot remove '...': No such file or directory

This happens because we are trying to remove a file that we recently moved so it don't exists anymore. We can fix it by remove `rm`, add `rm -f` or replace `rm` and `rmdir` by `rm -rf`.

https://github.com/bpg/terraform-provider-proxmox/blame/46d09f7e980fa9a981b81000fa4bdffc823558fc/proxmoxtf/resource/file.go#L596

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm %s/%s && rmdir -p %s`,
				trySudo,
				srcDir, *fileName,
				dstDir, *fileName,
				srcDir, *fileName,
				srcDir,
			),
```

Possible solutions snippets:

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir -p %s`,
				...
			),
```

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm -f %s/%s && rmdir -p %s`,
				...
			),
```

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm -rf %s`,
				trySudo,
				srcDir, *fileName,
				srcDir, *fileName,
				srcDir,
			),
```

### PR DESCRIPTION
**Pull request by ecanuto**
When trying to create a file using `proxmox_virtual_environment_file` we got an error:

```terraform
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.proxmox_node_name
  overwrite    = true

  source_file {
    path      = "cloudinit.yaml"
    file_name = "debian12.cloud-config.yaml"
  }
}
```

```
Error: error moving file: rm: cannot remove '...': No such file or directory
```

As discussed on (#1011) The use of `rm -rf` on tempFileDir solves the problem and also cleanup temp folder.

### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1011 | Relates #1011

### CODE REVIEW

**Comment by otopetrik** [comment]
It would be more safe in the future to avoid using `rm -rf`.
This:
```
fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir %s`,
	trySudo,
	srcDir, *fileName,
	dstDir, *fileName,
	tempFileDir,
),
```
would probably work, the `tempFileDir` should be empty.

**Comment by ecanuto** [comment]
> It would be more safe in the future to avoid using `rm -rf`. This:
> 
> ```
> fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir %s`,
> 	trySudo,
> 	srcDir, *fileName,
> 	dstDir, *fileName,
> 	tempFileDir,
> ),
> ```
> 
> would probably work, the `tempFileDir` should be empty.

No, don't works because tempFileDir don't include `snippets` folder on it. We can have one rm and two rmdir`s but will fail when request.ContentType is null.

I know that people are scared about `rm -rf` but the in this way, it is just a rmdir recursive.

**Comment by ecanuto** [comment]
> It would be more safe in the future to avoid using `rm -rf`. This:
> 
> ```
> fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir %s`,
> 	trySudo,
> 	srcDir, *fileName,
> 	dstDir, *fileName,
> 	tempFileDir,
> ),
> ```
> 
> would probably work, the `tempFileDir` should be empty.

Have updated the PR with:

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir %s && rmdir %s`,
				trySudo,
				srcDir, *fileName,
				dstDir, *fileName,
				srcDir,
				tempFileDir,
			),
```

Tested and it works.

**Review by bpg — APPROVED** [review]
Thank a lot @ecanuto! I really appreciate you taking the time to dig into the problem and proposing a solution 👍🏼 

I've just made a small improvement to handle the case when `request.ContentType` is empty.

LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @ecanuto for code

**Pull request merged**
