### PR TITLE
docs: refactor around token use

### PR DESCRIPTION
**Pull request by windowsrefund**
Trying to improve the documentation in the following ways:

- Keep things DRY.
- Stop advocating the use of root.
- Advocate for the use of API tokens and being tracking the role permissions needed.
- Eliminate ambiguous lingo around any ssh limitations and (outdated?) requirements. If there are indeed limitations, they should be clearly communicated.

If approved, I'll take a stab at minimizing this repo's README.md so things don't overlap and conflict with each other.

### CODE REVIEW

**Comment by otopetrik** [comment]
Thanks for looking at the documentation, unfortunately there are some problems with this PR.

> - Keep things DRY.

Generally good principle, but not at the cost of making it harder for beginners to use the provider. See section "example" further down.

> - Stop advocating the use of root.

It should be documented how to switch to non-root PAM user, but there are real obstacles in switching from root.

> - Advocate for the use of API tokens and being tracking the role permissions needed.

Documenting how to configure token using CLI is great, but they should be generated for PAM users `username@pam`, because ssh access is likely needed anyway.
Uploading snippets at the moment seems to require ssh, which needs correct permissions on storage directories on the hosts.
That makes this type of configuration recommended for *production* use, but not for beginners.

Using (root) username and password (preferably through `PROXMOX_VE_USERNAME` and `PROXMOX_VE_PASSWORD` or a gitignored .tfvars file) should be the default *starting point* for users just beginning to use the provider.

> - Eliminate ambiguous lingo around any ssh limitations and (outdated?) requirements. If there are indeed limitations, they should be clearly communicated.

That is just wrong, that information is relevant and should **not** be deleted.

- *Note1* is clear, when using `api_tokens` and `ssh`, provider needs to know which PAM user to use when connecting over ssh. This is _very_ useful infromation.
- *Note2* is not specific, because there is no list of all attributes of all API calls that may fail when called with an API token. But it shows an example of the error, and what causes it (using `api_token` with something that does not support it). Looks like earlier this year another case was discovered #344

**the example**

A complete provider configuration example at the top **should stay**.
After this patch, there does not seem to be any *complete provider configuration example*, and none of the example fragments show `endpoint` in use, because all the fragments silently assume that `PROXMOX_VE_ENDPOINT` environment variable is set.

This bit by bit type of documentation probably works for user who already uses the provider and wants to switch from `username` and `password` to `api_token`, but it will only frustrate new users.

The example of provider configuration at the top should be ***ready for copy-and-paste*** by a user just starting to learn how to use the provider.
Though it might be good idea to add comments to the example, to remind the user to migrate to a better configuration once they get the provider working, something like:
```terraform
provider "proxmox" {
  endpoint = "https://10.0.0.2:8006/"
  # TODO: use terraform variable or remove the line, and use PROXMOX_VE_USERNAME environment variable
  username = "root@pam"
  # TODO: use terraform variable or remove the line, and use PROXMOX_VE_PASSWORD environment variable
  password = "the-password-set-during-installation-of-proxmox-ve"
  # because self-signed TLS certificate is in use
  insecure = true
  # uncoment (unless on Windows...)
  # tmp_dir  = "/var/tmp"

  ssh {    
    agent = true
    # TODO: uncomment and configure if using api_token instead of password
    # username = "root"
  }
}
```

The example at the top actually *gets used* by the users, see just few days old issue https://github.com/bpg/terraform-provider-proxmox/issues/623  caused by the example being written with silent assumption that terraform is running on a non-Windows machine.

**root**

Unfortunately, in some cases Proxmox requires `root` when calling API.
And even full `root` token (e.g. `root@pam!token123=uuid` without privilege separation) does not seem to be enough.
Some time ago I tried to use such token, and if I remember correctly, creating a 32-bit VM failed on Proxmox API call, it required `root` user and password.

It is possible that something changed on Proxmox side, or that there are *other* cases that also require "real root".
Deleting existing notes about such behavior would just force users to rediscover it the hard way.

*Please do not delete the note, unless you have actually verified that creating VM (and container) with 'cpu architecture' set to non-default value works when using `api_token`.*
The documentation about limitations of `api token` (i.e. **Note2**) is non-specific, because it is based on observation. It does not seem to be documented by Proxmox, so it is possible that there are other actions that can fail when using api_token, and require root.

While using `username` and `password` is **not** ideal, suggesting `api_token` being the best approach is misleading as long as ssh is still required to fully use of the provider (ssh snippets upload to root owned directory).

When first learning to use the provider, using just `username` and `password` simply has much higher chance of success. 

**api_token**

When using `api_token`, the `ssh` block should have `username` configured, this information is missing after deletion of **Note1**.

The new version of documentation would leave users using `api_token` without the ability to upload `proxmox_virtual_environment_file` with `snippets` content type (unless there were some recent changes and Proxmox started allowing uploading snippets over API).
That would leave the provider unable to create VM configured using custom cloud-init files (the `user_data_file_id` vm attribute), which is an important capability enabled by this provider.

Documenting `api_token` configuration using CLI instead of GUI is **great**!
Maybe the solution is to have separate page for "production configuration" - how to create PAM users, configure storages, set directory permissions, setup proxmox pools, create multiple limited `api_tokens` for PAM users.

**privileges & tokens**

It might be good idea to link Proxmox [privileges documentation](https://pve.proxmox.com/pve-docs/pveum.1.html#_privileges). Possibly noting that the list is a suggestion. (e.g. missing `User.Modify` is required for `proxmox_virtual_environment_user`)

Not sure about creating a separate user with list of privileges, and then creating a `--privsep=0` token which gets *all* the user's privileges. Especially if the user still needs a PAM username for ssh for practical use.

Generally there are existing system (PAM) users for SSH access (at least `root`).
It might be better idea to guide user how to create tokes for their existing PAM user (not necessarily root), and limit privileges on *token* level, using privilege separation and a list of privileges. (e.g. `username@pam!terraform_experiment01=uuid` and `username@pam!terraform_homelab=uuid` with different permissions, possibly limited to different pools)

**Comment by windowsrefund** [comment]
I can't even begin to tell you how much I disagree with so much of what you've stated. Given the degree of conviction you seem to have around advocating bad practices (using root) and leaving ambiguous and assuming workflows in place, I have little faith this documentation will ever be made accurate or valuable. I'll just leave this sit here though in case someone wants to move the ball forward.

Still though, great provider! Many thanks for all your hard work.

**Comment by otopetrik** [comment]
Sorry if it seems like I think that using api tokens is bad idea, from security standpoint using tokens instead of passwords is _good_ idea.

And as I have written above, extending the documentation to provide better guidance how to use CLI for `api_token` generation is **great**!
Though that single sentence probably got drowned in that wall of text.


I think that the main point of difference is that you assume that configuring the provider to use only api tokens still enables (almost?) the same full functionality as using username and password (and SSH). Unfortunately that is not the case:

1. Some Proxmox API calls will fail when using _any_ API token instead of root username and password. Some could be considered mostly irrelevant (e.g. creating 32-bit VM), but there are other _very_ useful functionality gated on `root@pam` not yet implemented in the provider. E.g. ["hookscript"](https://forum.proxmox.com/threads/script-only-root-may-set-this-option.75775/)

Proxmox seems to be working towards allowing that using API tokens (a 'Sys.Root' privilege) for last 3 years, but [patch](https://bugzilla.proxmox.com/show_bug.cgi?id=2582) does not seem to be integrated yet.

4. Some operations are not available through Proxmox API at all, and the provider works around it by using SSH to connect directly to the Proxmox host(s). It could be considered a hack, but it does provide **critical** functionality (custom cloud-init).

Proxmox does have a [bug report](https://bugzilla.proxmox.com/show_bug.cgi?id=2208), but no patch.



I would very much like to be able to fully use the provider using only the `api_token` auth.
Unfortunately, at the moment Proxmox API limitations require the use of SSH to fully use the provider.



I do not know your use use case for the provider. For me, the ability to quickly test `cloud-init` configurations and templates on a locally hosted Proxmox machine is **the most important feature**.

At the moment, that requires provider with configured SSH (to upload the `cloud-init` configuration snippet).
Configured SSH requires a PAM username on the host. That PAM user has to have write access to the snippet directory of configured proxmox storage.


Compare following two ways to configure a fully functional provider:


1. root PAM user + password (both for API and SSH)

i.e.
```terraform
provider "proxmox" {
  endpoint = "https://10.0.0.2:8006/"
  username = "root@pam"
  password = "the-password-set-during-installation-of-proxmox-ve"
  insecure = true
  #tmp_dir  = "/var/tmp"
}
```

That is it. The provider is configured for initial exploration or homelab use.

And it is simple to modify it to something, that can be maintained in git, e.g.:

```terraform
provider "proxmox" {
  endpoint = var.pve_endpoint
  username = "root@pam"
  password = var.pve_root_password
}
```

That root password for API access can be in gitignored .tfvars file, secured using terraform-provider-sops or by some other secret keeping mechanism, and SSH root access can be switched over to SSH keys (and SSH password login disabled).

Assuming that the root password is long and randomly generated and proxmox API and SSH are properly firewalled, I consider that setup reasonably secure.


2. non-root PAM user + password (for SSH) and api_token (either username@pam or username@pve)
(which seems to be the only way to not use root user, use api_token and still have full functionality)

- configure api_token
- create PAM group for storage write access
- create non-root PAM user and SSH access using SSH key, add user to the group for storage write access
- change permissions to `/var/lib/vz/snippets` to allow write access to members of the group
  (and possibly other configured snippets storage)
- probably configure ulimits & quotas for the PAM user

The newly added PAM user does not have Proxmox API access, it is used only for snippet management over SSH.



My problem with proposed change is **not** that I consider the first way more secure. Assuming that ulimits and quotas _are_ set, the second way likely is more secure.

The problem is that the documentation change removes existing complete and easy-to-use example for the first (simplest) way, and does not even fully document how to set it up the second way.
Only the first step (configure api_token) is documented, the remainder is left for the user to figure out. Not only how to do it, but also what is actually needed to be done. The new version of the documentation does not leave the user with *any* complete documentation on how to get a **fully functional provider**.


I thing the best way would be to extend the documentation with additional section after 'Argument Reference', whith guide how to migrate from first way of configuration to the second.
(there does not seem to be a resource for api key, but there are `proxmox_virtual_environment_role` and `proxmox_virtual_environment_user` which cloud be useful)


The removal of Note1 and Note2 just made me annoyed, because it misled me into the assumption that you have not even tried the functionality described in 'SSH connection' section (e.g. to actually configure VM using a custom cloud-init `proxmox_virtual_environment_file`) before deleting the notes.
That annoyance translated into the response, sorry about that. I should have noticed I was tired and postponed writing a response to the next day.

**Comment by otopetrik** [comment]
> `--privsep=0` does not translate in the way you described. It relates to what namespaces (paths) are scoped to the privileges assigned to the token. It does not grant additional privileges in the way you suggest. Regarding privilege separation,tThat degree of permissions refactoring comes into play once the environment justifies it (multiple teams working on different parts of the infrastructure). In that world, you'd be managing multiple tokens (most likely used by different teams) and would want to limit their use to different paths accordingly. Right now, we're talking about the creation and use of 1 (the first) token so there would be no point to reducing it to subset of the tree (/).

Thanks, I did not know that privsep is tied to paths.
I just assumed that `privsep=0` means that token gets all the privileges of the user and that `privsep=1` could be used limit api token to fewer privileges.
E.g. user has `Sys.Modify`, but create api token for given terraform project without it, as it does not need to modify proxmox network configuration.
But it makes sense that it would also require limiting paths to achive required granularity.

> I can't even begin to tell you how much I disagree with so much of what you've stated. Given the degree of conviction you seem to have around advocating bad practices (using root, tying auth against PAM) and leaving ambiguous and assuming workflows in place, I have little faith this documentation will ever be made accurate or valuable. I'll just leave this sit here though in case someone wants to move the ball forward.

Please don't just leave it as is. Documenting an `api_token`-centric configuration of fully functional provider would be useful. It just should not be the initial way for a beginner to configure it.

> Given your convictions, I would only advocate maybe taking a day, start from scratch (get rid of all your root-based environment variables and hard-coded values). Use only an api token associated with a user+role in the pve realm. I think you'll see the majority of things will work fine. In the case something doesn't work, it should be documented as exactly what it is; an exception (rather than being used to lower the overall bar).

"majority of things" may work fine, but `proxmox_virtual_environment_file` is at the center of many workflows and requires SSH.

Terraform provider for libvirt seems to generate cloud-init iso [locally](https://github.com/dmacvicar/terraform-provider-libvirt/blob/6bf58621cf92ed1fe8111d8a8519fb00302ecca0/libvirt/cloudinit_def.go#L142), and ISO would be uploadable without SSH. But that would require `mkisofs` to be installed in addition to terraform.

Here is a [debiantest.tf](https://gist.github.com/otopetrik/f6e6ef79636592cab957407da1ac5f7b), a minimal VM configuration.

Please **try it**, you will see that `proxmox_virtual_environment_file` really is critical.

Terraform downloads debian cloud image, and creates a VM configured using custom cloud init configuration.
It uses public ssh-key from github to configure remote access.
Packages qemu-guest-agent, apache2 are installed.

Only thing missing from the gist is the provider configuration.

This:
```terraform
provider "proxmox" {
  endpoint  = var.pve_endpoint
  api_token = var.pve_api_token
  insecure  = var.pve_insecure
  ssh {
    username = "root"
    agent = true
  }
  tmp_dir = "/var/tmp"
}
```
works without changes on the Proxmox host.

Though it uses an api_token, it still requires root ssh key on the machine running terraform (likely negating security benefits of the token).
- Changing username to something else than 'root' requires changing directory permissions on server.
- Removing 'ssh' block makes it fail.

Btw. VM is configured with guest-agent enabled, if cloud-init fails to install it (e.g. network issue), it will not respond to stop commands from Proxmox. Use 'Monitor' tab of Proxmox GUI and enter 'quit' command to stop VM directly.

**Comment by windowsrefund** [comment]
I think you'll be surprised to see what doesn't work if you take a day and just remove your root username and password from your `provider` block. Only then, will you start to see the code itself is (at least somewhat) tied to the root user. Even when you give the provider a non-root user, binaries like `/usr/sbin/pvesm` can't be located/used. At a minimum, https://github.com/bpg/terraform-provider-proxmox/blob/4453ca6d7004ee58bba1a4770a1be8cace820957/proxmoxtf/resource/vm.go#L2748 should be passed into `sudo`.

So yea, I completely agree there's value in documenting according to well-established best practices but nobody can do that if the code itself depends on root.

**Comment by windowsrefund** [comment]
Here's the most minimal `provider` block I could get away with for the purpose of building a very simple `proxmox_virtual_environment_vm` resources from an image managed as a `proxmox_virtual_environment_file` resource:

```
provider "proxmox" {
  endpoint = "https://pve:8006"
  insecure = true
  ssh {
    node {
      name    = "pve"
      address = "192.168.1.200"
    }
    username = "root"
    agent    = true
  }
}
```

The above works since I've set my `PROXMOX_VE_API_TOKEN` environment variable.

My non-root public ssh key (loaded into ssh-agent) exists in pve:/root/.ssh/authorized_keys 

Even though this works, there are some obvious security no-nos going on here as well as some odd behaviors I know are being discussed [elsewhere](https://github.com/bpg/terraform-provider-proxmox/issues/126) among these issues:
- The whole IP resolution thing that forces me to override it in the `ssh` block.  Again, my spidey-sense tells me there's no good reason interface addresses need to be [collected via ssh](https://github.com/bpg/terraform-provider-proxmox/issues/126#issuecomment-1445258312) but I honestly don't know that for sure given my lack of understanding as to what the API provides.
- I've already seen `user_data_file_id` fail when I tried to use it so I'm sure there's something in there that'll need to be looked at.

**Comment by bpg** [comment]
This PR seems to be abandoned by the author, but there are lots of improvements in the diff and good points in the discussion.
I'll try re-combining bits and pieces from here into a new PR.

**Comment by bpg** [comment]
Superseded by #846

**Pull request closed without merging**
