### PR TITLE
feat(vm): efi disk, cpu numa

### LINKED ISSUE #316: Add EFI disk support
During `terraform apply`, version 0.18.1 of this provider fails with an error even though the VM creation is successful (there is only a warning):

`Error: task "UPID:myhost:00000000:00000000:00000000:qmstart:1000:me@domain:" on node "myhost" failed to complete with error: WARNINGS: 1`

I think that this is the responsible line:

https://github.com/bpg/terraform-provider-proxmox/blob/7c9505d11f7cc99f6052e814f549004fe97e8b49/proxmox/virtual_environment_nodes.go#L297

The web interface (Proxmox 7.4-3) gives the details of the warning:

```
generating cloud-init ISO
WARN: no efidisk configured! Using temporary efivars disk.
TASK WARNINGS: 1
```

The obvious workaround is to add an EFI disk to the VM template (I have to use the Proxmox UI for this, because configuration of an EFI disk doesn't seem to be supported, see https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/resources/virtual_environment_vm.md).

However, if I do this, then I'm hit by issue #314. And unfortunately, it doesn't seem to be possible to change the EFI disk size in Proxmox - it will always use k or M units.

Because `terraform apply` was not successful, it will destroy the resource on the next try, so I cannot move forward.

Do you know a workaround or fix?

Thank you for this project and your efforts, much appreciated.

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
### Description
Adds support for configuring the efi disk & numa for a VM

```
resource "proxmox_virtual_environment_vm" "vm" {
  cpu {
    numa: true
  }

  efi_disk {
    datastore_id = "local-zfs"
    size = "4M"
  }
}
```

### Contributor's Note
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/examples` for any new or updated resources / data sources.
- [ ] I have ran `make examples` to verify that the change works as expected. 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #316

### CODE REVIEW

**Comment by bpg** [comment]
Hey @ForsakenHarmony! 👋🏼
Thank you so much for contributing this!

Would it be possible to extract the import support into a separate PR?

I'll take a close look at the code and run some tests in my lab in the next few days.

**Comment by ForsakenHarmony** [comment]
@bpg pulled out the import support

**Comment by bpg** [comment]
> @bpg pulled out the import support

Thanks! 
I'm still testing this functionality. Hope you don't mind if I make a few adjustments to your PR :)

**Comment by ForsakenHarmony** [comment]
@bpg feel free to fix anything broken

**Review by bpg — APPROVED** [review]
I've made a few changes, most notable replacing `size` with `type` as per [PVE docs](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_configuration) only 2 sizes are supported (`2m` and `4m`)

But awesome work anyway, I really appreciate the PR! 🚀

**Pull request merged**
