### PR TITLE
fix(docs): fix wrong startup delay attributes

### PR DESCRIPTION
**Pull request by zmingxie**
### Contributor's Note
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Proof of Work

Simple fix for the docs to match the updated define

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #0000 | Relates #0000

### CODE REVIEW

**Comment by zmingxie** [comment]
Hmm... not sure what the Acceptance Tests are failing here. My PR only updates the docs

**Comment by bpg** [comment]
I've added them just few days ago, there are still some rough edges. Looks like it can't dispatch the test workflow from a forked repo.

**Comment by zmingxie** [comment]
> I've added them just few days ago, there are still some rough edges. Looks like it can't dispatch the test workflow from a forked repo.

Hmm... I've rebased my fork to pick up your latest changes, but It doesn't seem to help. Anyhow, my PR here just updates the doc. Could you merge it when you get a chance? Thanks!

**Review by bpg — APPROVED** [review]
Thanks for the fix @zmingxie!

LGTM! 🚀

**Pull request merged**
