### PR TITLE
fix(docs): Fix the generation path for "guides"

### PR DESCRIPTION
**Pull request by svengreb**
### Contributor's Note
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Summary

Fixes the path where the "guides" are generated within the `docs` directory. Before they were placed in `docs/guides/guides` which is a unnecessarily nested folder with the same name.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by bpg** [comment]
Hm... I didn't notice that 🤔 
With the current code before this change:
```
❯ make docs
rendering website for provider "terraform-provider-proxmox" (as "terraform-provider-proxmox")
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "proxmox"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
getting provider schema
generating missing templates
generating missing resource content
resource "proxmox_virtual_environment_download_file" fallback template exists, creating template
resource "proxmox_virtual_environment_firewall_options" fallback template exists, creating template
...
data-source "proxmox_virtual_environment_user" fallback template exists, creating template
data-source "proxmox_virtual_environment_users" fallback template exists, creating template
data-source "proxmox_virtual_environment_vms" fallback template exists, creating template
generating missing function content
generating missing provider content
generating new template for "terraform-provider-proxmox"
rendering static website
cleaning rendered website dir
removing directory: "data-sources"
removing directory: "guides"
removing file: "index.md"
removing directory: "resources"
rendering templated website to static markdown
rendering "data-sources/virtual_environment_datastores.md.tmpl"
rendering "data-sources/virtual_environment_dns.md.tmpl"
...
rendering "data-sources/virtual_environment_vm.md.tmpl"
rendering "data-sources/virtual_environment_vms.md.tmpl"
rendering "guides/cloud-image.md.tmpl"
rendering "guides/cloud-init.md.tmpl"
rendering "guides/setup-proxmox-for-tests.md.tmpl"
rendering "index.md.tmpl"
rendering "resources/virtual_environment_certificate.md.tmpl"
rendering "resources/virtual_environment_cluster_firewall.md.tmpl"
...
rendering "resources/virtual_environment_vm.md.tmpl"
rendering "resources/virtual_environment_vm2.md.tmpl"
❯ tree docs
docs
├── data-sources
│   ├── virtual_environment_datastores.md
│   ├── virtual_environment_dns.md
...
│   ├── virtual_environment_vm.md
│   └── virtual_environment_vms.md
├── guides
│   ├── cloud-image.md
│   ├── cloud-init.md
│   └── setup-proxmox-for-tests.md
├── index.md
└── resources
    ├── virtual_environment_certificate.md
    ├── virtual_environment_cluster_firewall.md
 ...
    ├── virtual_environment_vm.md
    └── virtual_environment_vm2.md

4 directories, 54 files
```

I'm wondering if this is something OS-specific? What OS are you on?

**Comment by svengreb** [comment]
I use macOS for all "development environments" (where my terminal is my absolute main app that is always open 😁), but most of my base tools are not the BSD based ones (which macOS is based on) but I use [the Linux (GNU) `coreutils`](https://formulae.brew.sh/formula/coreutils) so basically my environment can be seen as a Linux system.

I took a deeper dive into [the POSIX specification for `cp`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cp.html) and I guess this is indeed a local problem again, but not a one specific to my environment.
The specification explains how `cp` should act depending on the type of source and destination [_inode_ type](https://en.wikipedia.org/wiki/Inode).

In short: The `go:generate` command in the `tools/tools.go` file uses the `cp` command first found in `$PATH` which is the one from the _Homebrew_ `coreutils` package (symlink to `/opt/homebrew/opt/coreutils/libexec/gnubin/cp`), but this one differs from the default BSD `cp` in the way that BSD is not full POSIX compatible. Add a dot at the end of the source path also "fixes" the problem on my system, so the full command would be `//go:generate cp -R ../build/docs-gen/guides/. ../docs/guides/`.

I guess a way to make this work on any system is to either copy each file on its own, which works with all implementations of `cp` (at least with [GNU](https://man.freebsd.org/cgi/man.cgi?cp) & [BSD](https://www.gnu.org/software/coreutils/manual/html_node/cp-invocation.html)), or with the destination directory name being removed like submitted in this PR since this behavior is also the same for all implementations.
The root problem of the current command is that trailing slashes are interpreted differently, just [like `rsync` also has special handling for those](https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-net-rsync.html#id-1.3.3.16.5.7).

In short: Feel free to close/discard this PR, I'm totally fine with simply deleting the duplicate directory on my side whenever I generate the docs 😃

One recommendation I can give, however, is that I'd generally avoid `make` for Go projects and stick to something like [Magefile](https://magefile.org). Using pure Go as a build tool avoids such problems because you can simply use Go's [`io`](https://pkg.go.dev/io) or [`ioutil`](https://pkg.go.dev/io/ioutil) package to copy files and directories. Instead of having to rely on the underlying OS to provide the "correct" implementation of base tools Go takes care of it by making the _syscalls_ directly. This way Go is basally your `cp` implementation with 100% POSIX/BSD/GNU/Unix etc. compatibility for all system Go runs on, which is almost everywhere (not on [Tamagotchis](https://en.wikipedia.org/wiki/Tamagotchi), yet, but who knows that the future brings 😁). my opinion might be a bit influenced because I use [Magefile](https://magefile.org) for everything and also [built my own tooling around it](https://github.com/svengreb/wand), but I would not recommend it if this wouldn't be the perfect solution (using the same language to build itself is always the best way). let me know if you're interested, I can port the `Makefile` to _Mage_ and the only thing that change is that `go run make.go COMMAND` would be the way to use it, without the need to install `make` and all of its dependencies and quirks.

**Comment by bpg** [comment]
Thank you for the comprehensive explanation, @svengreb!

I believe Magefile is the way forward. I've used it in a few private projects, and it has worked quite well for me. 

If you have the time to contribute towards porting the Makefile to Mage, I would greatly appreciate it! I suggest we omit all "example*" related targets (along with their dependencies) in the first cut of the Magefile.

With that in mind, I'm closing this PR then :)

**Comment by svengreb** [comment]
Nice to see that you already used it. I'm currently working on another feature (APT repository (de)activation), but will also start to port and use it during development 👍

**Pull request closed without merging**
