### PR TITLE
feat(provider): add DNS lookup fallback for node IP resolution

### PR DESCRIPTION
**Pull request by bpg**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #725

### CODE REVIEW

**Comment by balaji-dutt** [comment]
Sorry I'm not very familiar with `golang` so I could not determine what `nc.NodeName` represents. But does this PR handle DNS lookup based on the node FQDN, or it is expecting the shortname to have a DNS entry?

**Comment by bpg** [comment]
Hi @balaji-dutt!

The "name" in this context will be PVE node name (like [here](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#node_name) or [here](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#node_name)). Usually it is just a host short name, not FQDN.
The assumption is that the workstation the provider is running from is in the same domain with  PVE node(s), and it is able to resolve the node shortname using its configured DNS resolver. A typical use case is a home network with local DHCP and DNS with dynamic update support (or dnsmasq for majority of routers), and PVE is configured with dynamic IP.

**Comment by bpg** [comment]
If you want to use FQDN, you can [configure](https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/index.md#node-ip-address-used-for-ssh-connection) specific overrides for each PVE node name. The `address` attribute could be IP or FQDN.

**Comment by balaji-dutt** [comment]
> If you want to use FQDN, you can [configure](https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/index.md#node-ip-address-used-for-ssh-connection) specific overrides for each PVE node name. The `address` attribute could be IP or FQDN.

Thank you for pointing out the FQDN option @bpg! I missed that on the initial read thru of the documentation. Short name resolution does not work in my particular use case due to VLAN segregation, but I could use the FQDN Override option instead.

**Pull request merged**
