### PR TITLE
feat(vm): Add Win 11 as os type

### LINKED ISSUE #719: Win11 os type
When setting "win11" as operating system type we get an error message
Error: expected type to be one of ["l24" "l26" "other" "solaris" "w2k" "w2k3" "w2k8" "win7" "win8" "win10" "wvista" "wxp"], got win11

Requires win11 to the list of allowed os types

Workaround is to set to win10 and change it afterwards in proxmox web interface (option named Microsoft Windows 11/2022 is supported)

### PR DESCRIPTION
**Pull request by dark-vex**
### Contributor's Note

- [X] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected. 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #719

### CODE REVIEW

**Review by bpg — CHANGES_REQUESTED** [review]
Hi @dark-vex!

Thanks a lot for the PR!

I noticed the formatting is a bit off there (I guess there are spaces instead of tabs). Could you please run `make fmt` or `make lint` on your branch to fix that?

Thanks!

**Comment by dark-vex** [comment]
> Hi @dark-vex!
> 
> Thanks a lot for the PR!
> 
> I noticed the formatting is a bit off there (I guess there are spaces instead of tabs). Could you please run `make fmt` or `make lint` on your branch to fix that?
> 
> Thanks!

Yes absolutely, I've used spaces from `vi` editor, let me fix it, apologies!

**Review by bpg — APPROVED** [review]
LGTM!

**Comment by bpg** [comment]
@all-contributors please add @dark-vex for code

**Pull request merged**
