### PR TITLE
feat: add support for more disk size units

### LINKED ISSUE #86: Add support for "G", "M" etc. disk size unit spec
Currently the unit of `virtual_environment_vm.disk.size` parameter is "gigabytes". Add ability to specify different units using G/GB, M/MB notation.

```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 117, in resource "proxmox_virtual_environment_vm" "example_vm":
│  117:     size         = "300G"
│ 
│ Inappropriate value for attribute "size": a number is required.

```

### PR DESCRIPTION
**Pull request by zeddD1abl0**
### Contributor's Note
Please mark the following items with an [x] if they apply to your PR.
Leave the [ ] if they are not applicable, or if you have not completed the item.
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/examples` for any new or updated resources / data sources.
- [ ] I have ran `make examples` to verify that the change works as expected. 

### Community Note

Added multiple tests for all formats and for conflicting strings. As a value with no unit now reports gigabytes, I have changed that test as well. Petabytes is supported, but unlikely to be used.

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #86

### CODE REVIEW

**Comment by bpg** [comment]
Hey @zeddD1abl0!

While there is nothing wrong with this code change, and the `ParseDiskSize` function works as expected, it doesn't really affect the way how TF _template_ parameters are parsed, so I can't say it will close #86

If you search for usages of `ParseDiskSize` you may find it in the code that reads responses from the PVE API. I.e. when the provider reads a disc block from a VM state, like this one
Screenshot 2023-04-16 at 8 52 16 PM
it then parses the disk size from the string.

The templates (.tf files) and their arguments are going via quite a different route. Starting from the schema definition (see [example](https://github.com/bpg/terraform-provider-proxmox/blob/f4783f8cda701b6800403d50840240da6469fd38/proxmoxtf/resource/vm.go#L568-L574) for the VM schema), then reading it from the state [using something like this](https://github.com/bpg/terraform-provider-proxmox/blob/f4783f8cda701b6800403d50840240da6469fd38/proxmoxtf/resource/vm.go#L1685), and so on. As you may see, the types there are `int`, and assumption is that the size passed-in from the tf template is in gigabytes. 

To accept different size formats, we would need to change the data type in the schema from int to string, add a validation function to ensure the string is in the right format, and more. Changing the format of the existing argument could cause backward compatibility issues, and old templates that are already in use may stop working or even cause data loss. 
I'm not sure if the Terraform SDK provides any tools to handle this type of change in a graceful way, so I will need to take a look at the documentation.

I apologize for the lengthy explanation, but it is essential to properly handle issue #86. Please let me know if you want to continue pursuing this ticket. If not, it's also totally fine :) We can merge this PR as is, and leave the ticket open.

**Comment by zeddD1abl0** [comment]
Yeah, I'd started with that as my entry point, but I'd made an assumption that it was already being handled as you describe. Sorry for that. I should have paid more attention while I was reading the code. I'll take a look into it and I should have a solution in the near future.

**Comment by bpg** [comment]
Awesome, thank you!

**Comment by zeddD1abl0** [comment]
I've added some updates that I believe are correct, but I've struggled to understand the logic sometimes. Hopefully it lines up better now.

**Comment by bpg** [comment]
The backward compatibility is my biggest concern at the moment, and unfortunately I don't see a good way to solve it without introducing a new argument for size.

For example, if currently I have a template like this
```terraform
resource "proxmox_virtual_environment_vm" "example" {
  name      = "test"
  node_name = "pve"
  vm_id     = 99

  started = false

  disk {
    datastore_id = "local"
    interface = "virtio0"
    size = 10
  }
}
```
and try to run `terrafom apply` with the new version of the provider, it start complaining:
```
│ Error: expected type of size to be integer
│
│   with proxmox_virtual_environment_vm.example,
│   on main.tf line 11, in resource "proxmox_virtual_environment_vm" "example":
│   11:     size = 10
```

Which would force almost all current users of providers to modify their templates. 

After giving it some thoughts I think we can do a multi-step renaming to introduce the new format:
1. Add `size_gb` which is the same as `size`, and deprecate `size`, release the version
2. Remove `size` of type int, release the version
3. Add `size` of stype string that support the new format, and deprecate `size_gb`, release the version
4. Remove `size_gb`, release the version

[This article](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations) explains renaming / removal of the attributes.


But regardless, I really appreciate your help with the provider and your contribution. I'll be happy to accept the previous version of your PR, without the schema change. 
Then we can gradually introduce the new schema via separate PRs and version releases, all tied to and documented in #86.

**Comment by bpg** [comment]
Hey @zeddD1abl0! Do you need any help with this PR?

**Comment by zeddD1abl0** [comment]
I was actually thinking on this and wondering if I'd be better off cancelling this PR and starting a new one specifically just to do the change to the util ParseDiskSize. This started as a PR to adjust the size parsing and has evolved and then devolved and is now basically just the regex comment I made in the issue associated. Probably better to just start clean with a new branch and a new plan.

**Comment by bpg** [comment]
That's fine, let's do that. I see this PR also reverts a few changes that have already been merged into the `main`, so it will be easier to start fresh than tinkering with rebase.

**Pull request closed without merging**
