### PR TITLE
fix(vm): re-use ide, sata, and scsi cloud-init storage (#1083)

### LINKED ISSUE #1083: proxmox_virtual_environment_vm is not idempotent with cloud init drive datastore_id + interface
**Describe the bug**

When re-applying the same Terraform code with a Cloud Init drive with the `datastore_id` and `interface` arguments set, Terraform detects drift as these 2 arguments doesn't show in Terraform state.
Also, it triggers a reboot that is endless on Proxmox side : no output content.

**To Reproduce**

1. Create the resource stated in the example config.
2. Run `terraform plan`

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.titan will be created
  + resource "proxmox_virtual_environment_vm" "titan" {
      + acpi                    = true
      + bios                    = "ovmf"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + migrate                 = false
      + name                    = "test1"
      + network_interface_names = (known after apply)
      + node_name               = "my-proxmox"
      + on_boot                 = true
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-single"
      + started                 = true
      + stop_on_destroy         = false
      + tablet_device           = true
      + tags                    = [
          + "terraform",
          + "debian",
          + "debian12",
        ]
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = 1000

      + agent {
          + enabled = false
          + timeout = "15m"
          + trim    = false
          + type    = "virtio"
        }

      + clone {
          + full    = true
          + retries = 1
          + vm_id   = 1501
        }

      + cpu {
          + architecture = "x86_64"
          + cores        = 2
          + hotplugged   = 0
          + limit        = 0
          + numa         = true
          + sockets      = 1
          + type         = "kvm64"
          + units        = 1024
        }

      + disk {
          + cache             = "none"
          + datastore_id      = "SSD_MP510"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio0"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 10
          + ssd               = false
        }
      + disk {
          + cache             = "none"
          + datastore_id      = "SSD_MP510"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio1"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 5
          + ssd               = false
        }

      + initialization {
          + datastore_id = "SSD_MP510"
          + interface    = "scsi1"

          + ip_config {
              + ipv4 {
                  + address = "192.168.108.5/28"
                  + gateway = "192.168.108.1"
                }
            }
        }

      + memory {
          + dedicated = 2048
          + floating  = 0
          + shared    = 0
        }

      + network_device {
          + bridge      = "vmbr0"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 1008
        }

      + operating_system {
          + type = "l26"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.

```

3. Terraform apply

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.titan will be created
  + resource "proxmox_virtual_environment_vm" "titan" {
      + acpi                    = true
      + bios                    = "ovmf"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + migrate                 = false
      + name                    = "test1"
      + network_interface_names = (known after apply)
      + node_name               = "my-proxmox"
      + on_boot                 = true
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-single"
      + started                 = true
      + stop_on_destroy         = false
      + tablet_device           = true
      + tags                    = [
          + "terraform",
          + "debian",
          + "debian12",
        ]
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = 1000

      + agent {
          + enabled = false
          + timeout = "15m"
          + trim    = false
          + type    = "virtio"
        }

      + clone {
          + full    = true
          + retries = 1
          + vm_id   = 1501
        }

      + cpu {
          + architecture = "x86_64"
          + cores        = 2
          + hotplugged   = 0
          + limit        = 0
          + numa         = true
          + sockets      = 1
          + type         = "kvm64"
          + units        = 1024
        }

      + disk {
          + cache             = "none"
          + datastore_id      = "SSD_MP510"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio0"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 10
          + ssd               = false
        }
      + disk {
          + cache             = "none"
          + datastore_id      = "SSD_MP510"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio1"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 5
          + ssd               = false
        }

      + initialization {
          + datastore_id = "SSD_MP510"
          + interface    = "scsi1"

          + ip_config {
              + ipv4 {
                  + address = "192.168.108.5/28"
                  + gateway = "192.168.108.1"
                }
            }
        }

      + memory {
          + dedicated = 2048
          + floating  = 0
          + shared    = 0
        }

      + network_device {
          + bridge      = "vmbr0"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 1008
        }

      + operating_system {
          + type = "l26"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
proxmox_virtual_environment_vm.titan: Creating...
proxmox_virtual_environment_vm.titan: Still creating... [10s elapsed]
proxmox_virtual_environment_vm.titan: Still creating... [20s elapsed]
proxmox_virtual_environment_vm.titan: Creation complete after 27s [id=1000]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

4. Relaunch a terraform plan right away without changing anything

```
proxmox_virtual_environment_vm.titan: Refreshing state... [id=1000]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.titan will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "titan" {
        id                      = "1000"
        name                    = "test1"
        tags                    = [
            "debian",
            "debian12",
            "terraform",
        ]
        # (25 unchanged attributes hidden)

      ~ initialization {
          + datastore_id = "SSD_MP510"
          + interface    = "scsi1"

            # (1 unchanged block hidden)
        }

      - vga {
          - enabled = true -> null
          - memory  = 0 -> null
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

5. The state for the resource

```
# proxmox_virtual_environment_vm.titan:
resource "proxmox_virtual_environment_vm" "titan" {
    acpi                    = true
    bios                    = "ovmf"
    id                      = "1000"
    ipv4_addresses          = []
    ipv6_addresses          = []
    keyboard_layout         = "en-us"
    mac_addresses           = [
        "BC:24:11:63:9D:58",
    ]
    migrate                 = false
    name                    = "test1"
    network_interface_names = []
    node_name               = "my-proxmox"
    on_boot                 = true
    reboot                  = false
    scsi_hardware           = "virtio-scsi-single"
    started                 = true
    stop_on_destroy         = false
    tablet_device           = true
    tags                    = [
        "debian",
        "debian12",
        "terraform",
    ]
    template                = false
    timeout_clone           = 1800
    timeout_create          = 1800
    timeout_migrate         = 1800
    timeout_move_disk       = 1800
    timeout_reboot          = 1800
    timeout_shutdown_vm     = 1800
    timeout_start_vm        = 1800
    timeout_stop_vm         = 300
    vm_id                   = 1000

    agent {
        enabled = false
        timeout = "15m"
        trim    = false
        type    = "virtio"
    }

    clone {
        full    = true
        retries = 1
        vm_id   = 1501
    }

    cpu {
        architecture = "x86_64"
        cores        = 2
        hotplugged   = 0
        limit        = 0
        numa         = true
        sockets      = 1
        type         = "kvm64"
        units        = 1024
    }

    disk {
        cache             = "none"
        datastore_id      = "SSD_MP510"
        discard           = "ignore"
        file_format       = "raw"
        interface         = "virtio0"
        iothread          = false
        path_in_datastore = "vm-1000-disk-1"
        size              = 10
        ssd               = false
    }
    disk {
        cache             = "none"
        datastore_id      = "SSD_MP510"
        discard           = "ignore"
        file_format       = "raw"
        interface         = "virtio1"
        iothread          = false
        path_in_datastore = "vm-1000-disk-2"
        size              = 5
        ssd               = false
    }

    initialization {
        ip_config {
            ipv4 {
                address = "192.168.108.5/28"
                gateway = "192.168.108.1"
            }
        }
    }

    memory {
        dedicated = 2048
        floating  = 0
        shared    = 0
    }

    network_device {
        bridge      = "vmbr0"
        enabled     = true
        firewall    = false
        mac_address = "BC:24:11:63:9D:58"
        model       = "virtio"
        mtu         = 0
        queues      = 0
        rate_limit  = 0
        vlan_id     = 1008
    }

    operating_system {
        type = "l26"
    }

    vga {
        enabled = true
        memory  = 0
    }
}

```

6. Relaunch a terraform apply

```
proxmox_virtual_environment_vm.titan: Refreshing state... [id=1000]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.titan will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "titan" {
        id                      = "1000"
        name                    = "test1"
        tags                    = [
            "debian",
            "debian12",
            "terraform",
        ]
        # (25 unchanged attributes hidden)

      ~ initialization {
          + datastore_id = "SSD_MP510"
          + interface    = "scsi1"

            # (1 unchanged block hidden)
        }

      - vga {
          - enabled = true -> null
          - memory  = 0 -> null
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_vm.titan: Modifying... [id=1000]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 10s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 20s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 30s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 40s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 50s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m0s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m10s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m20s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m30s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m40s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 1m50s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m0s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m10s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m20s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m30s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m40s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 2m50s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m0s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m10s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m20s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m30s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m40s elapsed]
proxmox_virtual_environment_vm.titan: Still modifying... [id=1000, 3m50s elapsed]

Ctrl-C
```
Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.47.0"
    }
  }
}


provider "proxmox" {
  endpoint  = "https://proxmox.example.net:8006"
  api_token = "my-admin-token"
  insecure  = true
  tmp_dir   = "/var/tmp"
}

resource "proxmox_virtual_environment_vm" "titan" {
  name = "test1"
  tags = ["terraform", "debian", "debian12"]

  node_name = "my-proxmox"
  vm_id     = 1000

  agent {
    enabled = false
  }

  clone {
    vm_id = 1501
  }

  cpu {
    numa    = true
    cores   = 2
    sockets = 1
    type = "kvm64"
  }

  bios = "ovmf"

  memory {
    dedicated = 2048
  }

  disk {
    datastore_id = "SSD_MP510"
    file_format  = "raw"
    interface    = "virtio0"
    size         = 10
  }

  disk {
    datastore_id = "SSD_MP510"
    file_format  = "raw"
    interface    = "virtio1"
    size         = 5
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = "1008"
    model   = "virtio"
  }

  operating_system {
    type = "l26"
  }

  scsi_hardware = "virtio-scsi-single"

  initialization {
    datastore_id = "SSD_MP510"
    interface    = "scsi1"
    ip_config {
      ipv4 {
        address = "192.168.108.5/28"
        gateway = "192.168.108.1"
      }
    }

  }
}

```

**Expected behavior**

It should be no changes as I didn't do any modifications, either in Terraform or Proxmox side.

**Screenshots**

image
Even with Ctrl-C terraform, the reboot task still hangs on Proxmox side

**Additional context**
N/A

- Single  Proxmox: 8.1.4
- Provider version (ideally it should be the latest version): 0.47.0
- Terraform version: 1.7.4
- OS (where you run Terraform from): Arch Linux
- Debug logs (`TF_LOG=DEBUG terraform apply`): https://pastebin.com/VuwaqHZu

EDIT : actually, the `vga` block has the same issue, regardless of UEFI or BIOS firmware.

### PR DESCRIPTION
**Pull request by michaelfranzl**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

I'm a first-time contributor, so this PR might not be acceptable, but I'd appreciate if you'd help me along.

### Proof of Work

I have manually tested the described use case of #1083 against Proxmox, and found it working.

TODO: Automatic testing: Write an example targeting this use case.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1083

### CODE REVIEW

**Comment by bpg** [comment]
Hi @michaelfranzl 👋🏼

Thanks a lot for the PR! I really appreciate contributions! ❤️ 
I'll take a closer look a bit later in the week, we could probably simplify a few things there. As you mentioned, it would be nice to have this use case captured in the acceptance tests, i may be able to quickly add them as well.

In a meantime, would you mind signing DCO? You can find more information in [Details](https://github.com/bpg/terraform-provider-proxmox/pull/1141/checks?check_run_id=22893542432) of the failed DCO check.

**Comment by michaelfranzl** [comment]
I'll sign the DCO, and see if I can add acceptance tests as well.

**Comment by michaelfranzl** [comment]
@bpg In the first commit, I added a failing acceptance test. The failing test output is:

```
=== RUN   TestAccResourceVMInitialization                                                                 
=== RUN   TestAccResourceVMInitialization/initialization                                                  
    resource_vm_test.go:184: Step 1/1 error: After applying this test step, the non-refresh plan was not empty.                                                                                                     
        stdout:                                                                                           
                                                                                                          
                                                                                                          
        Terraform used the selected providers to generate the following execution                                                                                                                                   
        plan. Resource actions are indicated with the following symbols:                                                                                                                                            
          ~ update in-place                                                                               
                                                                                                          
        Terraform will perform the following actions:                                                     
                                                                                                          
          # proxmox_virtual_environment_vm.test_vm_network1 will be updated in-place                                                                                                                                
          ~ resource "proxmox_virtual_environment_vm" "test_vm_network1" {                                                                                                                                          
                id                      = "100"                                                           
                # (26 unchanged attributes hidden)                                                        
                                                                                                          
              ~ cpu {                                                                                     
                  + flags        = []                                                                     
                    # (8 unchanged attributes hidden)                                                     
                }                                                                                         
                                                                                                          
              ~ initialization {                                                                          
                  + datastore_id      = "local-lvm"                                                       
                  + interface         = "scsi1"                                                           
                    # (1 unchanged attribute hidden)                                                      
                                                                                                          
                    # (1 unchanged block hidden)                                                          
                }                                                                                         
                                                                                                          
                # (4 unchanged blocks hidden)                                                             
            }                                                                                             
                                                                                                          
        Plan: 0 to add, 1 to change, 0 to destroy.                                                        
--- FAIL: TestAccResourceVMInitialization (57.05s)                                                        
    --- FAIL: TestAccResourceVMInitialization/initialization (57.05s)                                                                                                                                               
FAIL                                                                                                      
FAIL    github.com/bpg/terraform-provider-proxmox/fwprovider/tests      57.052s                                                                                                                                     
FAIL
```

This output exactly reproduces what is reported in #1083.

The test then passes with the second commit, which only modifies the implementation.

**Review by bpg — APPROVED** [review]
Awesome work, much appreciated!

LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @michaelfranzl for code, test

**Pull request merged**
