### PR TITLE
fix(provider): maxint for storage and vms

### PR DESCRIPTION
**Pull request by DanielHabenicht**
### Contributor's Note
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected. (but I have tried it with the previously failing deployment and it works)

### Proof of Work
Comparable error to #685 just this time with `maxdisk`. As I have another VM on my proxmox instance with a 64GB disk which is again more than maxint, which led to the following error (after applying a normal VM plan) 
```
╷
│ Error: error retrieving VM status: failed to decode HTTP GET response (path: nodes/pve/qemu/102/status/current) - Reason: json: cannot unmarshal number 34359738368 into Go struct field GetStatusResponseData.data.maxdisk of type int
│
│   with proxmox_virtual_environment_vm.k8s_cp_01,
│   on main.tf line 45, in resource "proxmox_virtual_environment_vm" "k8s_cp_01":
│   45: resource "proxmox_virtual_environment_vm" "k8s_cp_01" {
│
```

Running the same terraform apply command with my patched version does the same without any errors. 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #0000 | Relates #0000

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Don't merge yet. I am encountering a crash with my version `Error: Plugin did not respond`

**Comment by bpg** [comment]
Hey @DanielHabenicht 👋🏼 

Thank a lot for the fixes!

> I am encountering a crash with my version:

I believe this may be due to the enabled debug logs. The [current logger](https://github.com/bpg/terraform-provider-proxmox/blob/3f582d816334d4db370e8a5124f27ae4842c93f1/proxmox/api/client.go#L83-L85) is dumping the full content of requests and responses into the log, and it seems to be doing so rather inefficiently. My guess is that it tries to read the entire file being uploaded into memory before logging it.

Regarding the PR, could you possibly split the documentation change into a separate PR?

**Comment by DanielHabenicht** [comment]
I split the documentation changes into #698. 

1. Your tip was right the overflow surely came from the debug logging. 
2. Still it masked another error which I now fixed by just not touching the memory types.
3. This now works for creating and destroying a VM. 

However, I am still concerned about the mapping from the terraform-sdk which still uses `int` type: 
https://github.com/bpg/terraform-provider-proxmox/blob/64c67d947362e2653feaab7fa9ffb3b6016d0650/proxmoxtf/resource/vm.go#L656-L662

and the later (or earlier) mapping to `int64`: `diskSize := diskBlock[mkResourceVirtualEnvironmentVMDiskSize].(int64)`.
I don't know whether this is relevant because I don't know the codebase, but just hope it's not and you can tell?

**Comment by bpg** [comment]
Something is a bit off with this code, the acceptance tests from `/example` fail with this error:
```
proxmox_virtual_environment_vm.example_template: Still creating... [10s elapsed]
proxmox_virtual_environment_vm.example_template: Creation complete after 11s [id=103]
╷
│ Error: error waiting for VM creation: task "UPID:pve:0015DA02:03540BFD:65502CC6:qmcreate:101:root@pam:" failed to complete with exit code: unable to create VM 101 - lvcreate 'pve/vm-101-disk-0' error:   Run `lvcreate --help' for more information.
│ 
│   with proxmox_virtual_environment_vm.data_vm,
│   on resource_virtual_environment_vm.tf line 195, in resource "proxmox_virtual_environment_vm" "data_vm":
│  195: resource "proxmox_virtual_environment_vm" "data_vm" {
│ 
╵
```
Perhaps something to do with the int conversion you've mentions above. I'll try to debug this a bit later.

**Review by bpg — APPROVED** [review]
Thanks for the PR @DanielHabenicht!
I fixed a few cases of wrong mapping, and removed confusing `SizeInt` attribute from `CustomStorageDevice` -- we can totally use `Size` instead.

LGTM! 🚀

**Comment by DanielHabenicht** [comment]
@bpg just a curious question on when it might get released?

**Comment by bpg** [comment]
@DanielHabenicht just merged your other PR, will publish a new release soon.

**Pull request merged**
