### PR TITLE
feat(vm): Support hook script

### LINKED ISSUE #570: Add support for hookscript
**Is your feature request related to a problem? Please describe.**
There is currently no way to set `hookscript` property of VM

**Describe the solution you'd like**
Add `hookscript` argument to [`proxmox_virtual_environment_vm`.](https://pve.proxmox.com/pve-docs/qm.1.html#_hookscripts), and probably to [`proxmox_virtual_environment_container`](https://pve.proxmox.com/pve-docs/pct.1.html#_hookscripts).

**Describe alternatives you've considered**
None.

**Additional context**
Hookscripts can be used ensure data safety:
- to reject VM start of data disk only VMs
- ensure that at most one VM (of a VM pair, both using same disks) is running. E.g. first VM is using gpu-passthrough, second using just SPICE - for use when completely different VM is using gpu-passthrough)

### PR DESCRIPTION
**Pull request by simplysoft**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected. 

### Proof of Work

Screenshot Add

```
$ cat /etc/pve/qemu-server/<vmid>.conf | grep hookscript
hookscript: local:snippets/<redacted>
```
Screenshot Remove

```
$ cat /etc/pve/qemu-server/<vmid>.conf | grep hookscript

```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #570

### CODE REVIEW

**Review by bpg-dev — COMMENTED** [review]
Hi @simplysoft 👋🏼 
Thanks a lot for contributing this feature!

The code looks good, but I have few suggestions :)

It probably would be better to rename the new attribute as `hook_scripts_file_id`, so it matches convention of other file references with have in the VM resource, for example, `user_data_file_id`, `network_data_file_id`, etc. 
A bit verbose, but gives an idea to the user that the content of a hook script attribute should be a reference to the file located on PVE.

Another thing is how this file is going to be created. As a TF user, I would expect to be able to have is a snippet `file` resource in my template, and then just reference is it in `hook_scripts_file_id`. However that won't work our of the box as the uploaded snippet won't be executable:
```
│ Error: error waiting for VM start: task "UPID:pve:003727C0:08FC020C:655EA78E:qmstart:100:root@pam:" failed to complete with exit code: hookscript error for 100 on pre-start: script 'local:snippets/hook-script.sh' is not executable
```
For better UX of the feature, and to avoid manual changing of file mode after uploads, I'd suggest adding a new `mode` attribute to the `file` resource, which then can be handled in ssh [NodeUpload](https://github.com/bpg/terraform-provider-proxmox/blob/388ce7ce8d37964da427d2430c9e03b14f790856/proxmox/ssh/client.go#L119) by calling `sftpClient.Chmod(remoteFilePath, mode)` after uploading the file. To pass the value down the stack I think it will be reasonable to add `Mode` field to the [FileUploadRequest](https://github.com/bpg/terraform-provider-proxmox/blob/80c94a51262df7c5cd49a938f58c7fd09a1a3540/proxmox/api/client_types.go#L28) struct.

Hope it makes sense, feel free to reach out if you have any questions!

**Comment by simplysoft** [comment]
Hi @bpg 
Thanks for the feedback, it aligns with our own thoughts as well, and having the option to use `file` resource to define them in TF would be really nice from a UX perspective.  
For this PR we went the quick & easy route and just plain exposed the hookscript field as we upload a set of scripts as part of the proxmox host provisioning (outside of terraform)

**Comment by bpg** [comment]
Hey @simplysoft, are you planning on making further changes in here? 

I'd really like to rename the argument to `hook_scripts_file_id` for consistency 🙂 

If you're not planning to do any file upload modifications, that's fine, but at least we have to document how/where to upload the file manually, and which permissions it should have.

**Comment by simplysoft** [comment]
We have made the renaming, although to `hook_script_file_id` as it is even more consistent we think. 

We have hoped we can invest some more time to implement the other suggested changes as part of this PR, but it didn't happened so far, so we can't promise anything for the time being. So probably best to merge this as a first step towards #570

**Comment by bpg** [comment]
> We have made the renaming, although to `hook_script_file_id` as it is even more consistent we think.
> 
> We have hoped we can invest some more time to implement the other suggested changes as part of this PR, but it didn't happened so far, so we can't promise anything for the time being. So probably best to merge this as a first step towards #570

Awesome, that works for me! 🙂

**Review by bpg-dev — APPROVED** [review]
LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @simplysoft for code

**Comment by benbouillet** [comment]
Hi @simplysoft !
First of all, thank you for your contribution to the project, it as clearly helped us managing our VMs way easily !
Did you have by any chance the opportunity to work on @bpg 's suggestion ? 

> Another thing is how this file is going to be created. As a TF user, I would expect to be able to have is a snippet `file` resource in my template, and then just reference is it in `hook_scripts_file_id`. However that won't work our of the box as the uploaded snippet won't be executable:
> 
> ```
> │ Error: error waiting for VM start: task "UPID:pve:003727C0:08FC020C:655EA78E:qmstart:100:root@pam:" failed to complete with exit code: hookscript error for 100 on pre-start: script 'local:snippets/hook-script.sh' is not executable
> ```

Thanks in advance for your answer !

**Comment by simplysoft** [comment]
@benbouillet no, we did not manage to find time to work on this

**Comment by svengreb** [comment]
@simplysoft @benbouillet I've submitted #1478 that implements the missing file mode functionality which is basically required to use hook scripts without manual interaction.

**Comment by benbouillet** [comment]
> @simplysoft @benbouillet I've submitted #1478 that implements the missing file mode functionality which is basically required to use hook scripts without manual interaction.

You rock, thank you!

**Pull request merged**
