### PR TITLE
fix(vm): Fixed missing default for disk discard

### PR DESCRIPTION
**Pull request by dandyrow**
The default value of "ignore" was missing from the disk discard parameter of the terraform module. This commit sets the default to "ignore" instead of the current "".

This fixes terraform incorrectly flagging that the state is different than what is currently running on the proxmox node when the discard option isn't defined under the disk object.

### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

### Proof of Work

Below shows the behaviour prior to the fix being applied:
image

Below shows the behaviour after the fix has been applied:
image

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by dandyrow** [comment]
Apologies for all the force pushing, just making sure my commit style matches with the expectations of the repo. I haven't seen commit messages quite like this on projects I've contributed to before.

**Review by bpg — APPROVED** [review]
Hi @dandyrow! 👋🏼 

Thanks for the fix!

While it solve the immediate issues, and it's totally fine to merge it in the current provider, we'd need to fix the root cause with "unwanted defaults".
For example, in the the following situation for a plan with `disk` like
```hcl
  disk {
    datastore_id = local.datastore_id
    file_format  = "raw"
    interface    = "scsi1"
    size         = 4
  }
```
the resource the provider creates is
Screenshot 2023-12-28 at 11 19 13 PM
`cache`, `discard`, `ssd`, etc. attributes should be omitted if they are defaults.

But for now: LGTM! 🚀

**Comment by bpg** [comment]
@all-c0ntributors, please add @dandyrow for code

**Comment by bpg** [comment]
h@all-contributors, please add @dandyrow for code

**Comment by bpg** [comment]
@all-contributors, please add @dandyrow for code

**Pull request merged**
