### PR TITLE
fix(file): display warning if directory is not found

### LINKED ISSUE #691: customized snippets not supported warning is not shown
**Describe the bug**
Instead of displaying the customized error message shown in #370 terraform reports a 'file does not exist' error.

**To Reproduce**

1. Freshly installed proxmox.
Alternatively: Disable 'Datacenter>Storage>local' content type 'snippets'  and delete folder `/var/lib/vz/snippets/` on the node. (seems like a bare installation does not have this folder by default)
2. Try create snippets resource
```
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data = <<EOF
#cloud-config
chpasswd:
  list: |
    ubuntu:example
  expire: false
hostname: example-hostname
packages:
  - qemu-guest-agent
users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSbM+h0IAyf0uY6NQgyHj80IDwyPsmRpuoOXT6mkEqG05xCBk28iXsqgofP+4RXQFjHSFmQf+9Jb+TtQfg938fq6Nok+G3/iTQJAP+YlC+1nomup5iBRBb7BDJqtDJJPxgFo6J8xx+Ivcuy9xEwenbsEX6NNCNCtCsG8301R26MdYePz0BjPO+krfojI1pVyLH2rN6NcDiUM9FwZV2SYFRiVxEvdbGt6kqcLZAISN0Gq761MU0nVMCbQYkmq78Rzo2hZMYShHmhsLqIlH3A0zyznp8huYBe6PX/Tg1Vwm6193YTPmqnNmC+ibMD87PbdzizLKz3lncUKDTF2H0+7xVr2SanDzfYNfKIEPVO8ud1QXvWzxcdXWyzCjhomEbKPMjQIg6Dlz59lukX/geb2XYDOs9XEYsri/rhfXyrUJY0w5fgse1/PEH+1V3mgr1KN5zpinudijEyGE02dcKS8me5RIx9TUPlk5BXRgDAWVmkbtJSncODfo5ha10DvZJtKk=
    sudo: ALL=(ALL) NOPASSWD:ALL
EOF

    file_name = "example.cloud-config.yaml"
  }
}
```
3. Run `terraform apply`
6. See error
```
 terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_file.cloud_config will be created
  + resource "proxmox_virtual_environment_file" "cloud_config" {
      + content_type           = "snippets"
      + datastore_id           = "local"
      + file_modification_date = (known after apply)
      + file_name              = (known after apply)
      + file_size              = (known after apply)
      + file_tag               = (known after apply)
      + id                     = (known after apply)
      + node_name              = "pve"
      + overwrite              = true
      + timeout_upload         = 1800

      + source_file {
          + changed  = false
          + insecure = false
          + path     = "cloud-init/user-data.yml"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_file.cloud_config: Creating...
╷
│ Error: failed to create file /var/lib/vz/snippets/user-data.yml: file does not exist
│
│   with proxmox_virtual_environment_file.cloud_config,
│   on main.tf line 52, in resource "proxmox_virtual_environment_file" "cloud_config":
│   52: resource "proxmox_virtual_environment_file" "cloud_config" {
│
╵
```

**Expected behavior**
It probably should show something like this: 
```
╷
│ Warning: the datastore "local" does not support content type "snippets"
│
│   with proxmox_virtual_environment_file.test_file,
│   on main.tf line 1, in resource "proxmox_virtual_environment_file" "test_file":
│    1: resource "proxmox_virtual_environment_file" "test_file" {
│
╵
```

**Screenshots**

**Additional context**
Single or clustered Proxmox: Single
Provider version (ideally it should be the latest version): 0.37.0
Terraform version: v1.3.7
OS (where you run Terraform from): Windows 10
Debug logs (TF_LOG=DEBUG terraform apply):
Proxmox Virtual Environment 8.0.4

### PR DESCRIPTION
**Pull request by DanielHabenicht**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected. 
- [x] Tested locally with snippets ressource.

### Proof of Work
image

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #691

### CODE REVIEW

**Review by bpg — APPROVED** [review]
Thanks a lot for the fix, @DanielHabenicht!

LGTM! 🚀

**Comment by bpg** [comment]
@DanielHabenicht Could you please sign-off you commit with your name and email, i.e. `Signed-off-by: Random J Developer <random@developer.example.org>`? You can use GH email alias xxx@users.noreply.github.com for privacy.

**Comment by DanielHabenicht** [comment]
Isn't it signed off? I explicetly added the flag when committing. Could be that codespaces does not do it in the right format?
I will have a look tomorrow, its sleeping time over here.

**Comment by bpg** [comment]
It show generic "GitHub ..."
Screenshot 2023-11-09 at 6 56 47 PM

**Comment by bpg** [comment]
@all-contributors please add @DanielHabenicht for code

**Pull request merged**
