### PR TITLE
feat(vm): support stopping (rather than shutting down) VMs on resource destroy

### PR DESCRIPTION
**Pull request by ActualTrash**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #0000 | Relates #0000

### CODE REVIEW

**Comment by bpg** [comment]
Thanks so much for the PR, @ActualTrash!

I've updated the PR title in accordance with the [coding convention](https://github.com/bpg/terraform-provider-proxmox/blob/main/CONTRIBUTING.md#coding-conventions). However, could you please also sign off on the commits? It may easier to rebase on main with squash, so there will be only one commit to sign off on.
Also, would you mind addressing linter errors?

Thanks!

**Comment by ActualTrash** [comment]
Everything should be good to go now. Let me know if anything else needs to be updated!

**Review by bpg — APPROVED** [review]
LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @ActualTrash for code

**Pull request merged**
