### PR TITLE
feat(vm): add support for USB devices passthrough

### LINKED ISSUE #665: USB Passthrough Support
**Is your feature request related to a problem? Please describe.**

I have some USB devices I need to pass through to virtual machines created by this provider. Currently, I need to create the VM and pass through the device using the PVE UI manually. That way, no full automation is possible.

**Describe the solution you'd like**

The PVE API supports defining USB device passthroughs. It would be great if the provider can be extended to support that.

The API provides a `usb[n]` parameter:

usb[n] | string |   | [[host=]<HOSTUSBDEVICE\|spice>] [,mapping=<mapping-id>] [,usb3=<1\|0>] | Configure an USB device (n is 0 to 4, for machine version >= 7.1 and ostype l26 or windows > 7, n can be up to 14).
|-- | -- | -- | -- | --|

**Describe alternatives you've considered**

Same process as currently: manual attachment. This doesn‘t solve the problem that full automation is never possible.

**Additional context**

It‘s clear that having host USB devices passed through limits migration possibilities and where the machine can be started. However, having the option to do so allows full automation of additional use cases.
In my case, I have Z-Wave and Zigbee controllers and an UnRaid USB device to pass through to some machines. Those devices are always connected by default to one PVE node anyways.

### PR DESCRIPTION
**Pull request by muhlba91**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected. 

### Proof of Work

vm.tf

```
resource "proxmox_virtual_environment_vm" "data_vm" {
  name      = "terraform-provider-proxmox-data-vm"
  node_name = "pve"
  started   = false
  on_boot   = false

  disk {
    datastore_id = "storage-pool"
    file_format  = "raw"
    interface    = "scsi0"
    size         = 1
  }
  usb {
    host = "0781:55a3"
    usb3 = false
  }
}
```

terraform plan:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.data_vm will be created
  + resource "proxmox_virtual_environment_vm" "data_vm" {
      + acpi                    = true
      + bios                    = "seabios"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + migrate                 = false
      + name                    = "terraform-provider-proxmox-data-vm"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + on_boot                 = false
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-pci"
      + started                 = false
      + tablet_device           = true
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = (known after apply)

      + disk {
          + cache             = "none"
          + datastore_id      = "storage-pool"
          + file_format       = "raw"
          + interface         = "scsi0"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 1
          + ssd               = false
        }

      + usb {
          + host = "0781:55a3"
          + usb3 = false
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.
```

terraform apply:

```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_vm.data_vm: Creating...
proxmox_virtual_environment_vm.data_vm: Creation complete after 1s [id=105]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

terraform refresh:

```
proxmox_virtual_environment_vm.data_vm: Refreshing state... [id=105]
```

screenshot of the hardware in the VM:
Screenshot 2023-10-30 at 9 17 36 AM

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #665

### CODE REVIEW

**Comment by muhlba91** [comment]
@bpg any chances to get this reviewed (and merged) for the next release?

**Review by bpg — APPROVED** [review]
Thank you so much @muhlba91 for adding this!
Great job putting together tests and proof of work, much appreciated.

LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @muhlba91 for code

**Comment by muhlba91** [comment]
thanks a lot for the fast merge and release! 👍🏻

**Pull request merged**
