### PR TITLE
fix(vm): state drift due to disk re-ordering

### LINKED ISSUE #185: VM Disks are getting reordered on apply causing VM re-creation
**Describe the bug**
If VM has multiple disks defined, applying the same template second time may cause VM recreation, as provider thinks that the disks have changed.

**To Reproduce**
1. Define a VM template with multiple disks, for example
```
  disk {
    datastore_id = local.datastore_id
    file_id      = proxmox_virtual_environment_file.ubuntu_cloud_image.id
    interface    = "virtio0"
    iothread     = true
  }

  disk {
    datastore_id = local.datastore_id
    interface    = "scsi0"
    discard      = "on"
    ssd          = true
  }

  disk {
    datastore_id = "nfs"
    interface    = "scsi1"
    discard      = "ignore"
    file_format  = "raw"
  }
``` 
2. Apply the template with `terraform apply`
3. Without any changes to the template, run apply again
4. Notice that terraform detected changes in the template:
Screenshot 2022-12-13 at 6 01 22 PM

**Expected behavior**
A second apply of the template without any changes should cause no-op from terraform.

**Additional context**
Order of disks in PVE UI after appy:
Screenshot 2022-12-13 at 6 17 45 PM
This seems to be a reason for the mismatch.

**Workaround**
Manually re-order disks in the template to match the order expected by PVE (alphabetically by interface name)

### PR DESCRIPTION
**Pull request by bpg**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Proof of Work

No changes detected with this plan:
```hcl
resource "proxmox_virtual_environment_vm" "test_disk_order-185" {
  node_name = "pve"
  started   = false
  name 	    = "test-disk4"
  template  = "true"

  disk {
    file_format  = "raw"
    datastore_id = "local-lvm"
    interface    = "virtio0"
    size         = 8
  }
  disk {
    file_format  = "raw"
    datastore_id = "local-lvm"
    interface    = "scsi0"
    size         = 8
  }
}
```

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #185

### CODE REVIEW

**Comment by luis-guimaraes-exoawk** [comment]
Sorry to necrobump, but it seems like this hasn't been fixed yet. I tried the latest version of the provider (0.55.0) and I still get the same problem as before due to the `path_in_datastore` getting replaced

**Comment by bpg** [comment]
Hey @luis-guimaraes-exoawk, not sure if your comment about `path_in_datastore` is related to this ticket?
Can you post your error message and template here, or perhaps open a new ticket?

**Comment by AtaLuZiK** [comment]
I have the same problem, first use step1.tf create vm and I find that virtio slot and disk are not in the same order

[step1.tf.txt](https://github.com/bpg/terraform-provider-proxmox/files/15271052/step1.tf.txt)



Then change one of the disks, such as set cache on swap, it look liks:
```
# Swap
disk {
  datastore_id = "local-lvm"
  interface    = "virtio1"
  file_format  = "raw"
  size         = 1
  discard      = "on"
  cache        = "unsafe" # <------- Here
}
```

After plan I got
```
  # proxmox_virtual_environment_vm.debian12dev-test must be replaced
-/+ resource "proxmox_virtual_environment_vm" "debian12dev-test" {
      ~ id                      = "109" -> (known after apply)
      ~ ipv4_addresses          = [
          - [
              - "127.0.0.1",
            ],
          - [
              - "192.168.9.6",
            ],
          - [
              - "172.18.1.2",
            ],
        ] -> (known after apply)
      ~ ipv6_addresses          = [
          - [
              - "::1",
            ],
          - [
              - "fe80::be24:11ff:fe7e:d60",
            ],
          - [
              - "fe80::be24:11ff:fed8:68dd",
            ],
        ] -> (known after apply)
      ~ mac_addresses           = [
          - "00:00:00:00:00:00",
          - "BC:24:11:7E:0D:60",
          - "BC:24:11:D8:68:DD",
        ] -> (known after apply)
        name                    = "debian12dev-test"
      ~ network_interface_names = [
          - "lo",
          - "eth0",
          - "eth1",
        ] -> (known after apply)
        tags                    = [
            "opentofu",
            "rust",
        ]
      ~ vm_id                   = 109 -> (known after apply)
        # (21 unchanged attributes hidden)

      ~ cpu {
          - flags        = [] -> null
            # (8 unchanged attributes hidden)
        }

      ~ disk {
          ~ file_format       = "raw" -> (known after apply)
          + file_id           = "nas-pve-data:iso/debian-12-genericcloud-amd64-20240429-1732.img" # forces replacement
          ~ interface         = "virtio1" -> "virtio0"
          ~ path_in_datastore = "vm-109-disk-0" -> (known after apply)
          ~ size              = 1 -> 8
            # (8 unchanged attributes hidden)
        }
      ~ disk {
          ~ cache             = "none" -> "unsafe"
          ~ interface         = "virtio2" -> "virtio1"
          ~ path_in_datastore = "vm-109-disk-1" -> (known after apply)
          ~ size              = 16 -> 1
            # (8 unchanged attributes hidden)
        }
      ~ disk {
          - file_id           = "nas-pve-data:iso/debian-12-genericcloud-amd64-20240429-1732.img" -> null # forces replacement
          ~ interface         = "virtio0" -> "virtio2"
          ~ path_in_datastore = "vm-109-disk-2" -> (known after apply)
          ~ size              = 8 -> 16
            # (9 unchanged attributes hidden)
        }

      ~ initialization {
          - interface         = "ide2" -> null
            # (3 unchanged attributes hidden)

            # (2 unchanged blocks hidden)
        }

      ~ network_device {
          - disconnected = false -> null
          ~ mac_address  = "BC:24:11:7E:0D:60" -> (known after apply)
            # (8 unchanged attributes hidden)
        }
      ~ network_device {
          - disconnected = false -> null
          ~ mac_address  = "BC:24:11:D8:68:DD" -> (known after apply)
            # (8 unchanged attributes hidden)
        }

        # (3 unchanged blocks hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy
```

Running it a few times without more changes has a probability of getting the correct result:

```
  # proxmox_virtual_environment_vm.debian12dev-test will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "debian12dev-test" {
        id                      = "109"
        name                    = "debian12dev-test"
        tags                    = [
            "opentofu",
            "rust",
        ]
        # (26 unchanged attributes hidden)

      ~ disk {
          ~ cache             = "none" -> "unsafe"
            # (11 unchanged attributes hidden)
        }

        # (9 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I can't guess what's causing this, so I'm trying to set up a development environment to debug this problem, but it seems like it's going to take me a long time with no experience

**Comment by bpg** [comment]
OK, I'm reopening #185 then.

**Pull request merged**
