### PR TITLE
fix(provider): typo in provider example

### PR DESCRIPTION
**Pull request by zmingxie**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #0000 | Relates #0000

👋 New to this repo, and I just spotted this typo when I was going over the code.

### CODE REVIEW

**Comment by bpg** [comment]
Hi @zmingxie! 👋🏼 
Thank you for the the fix!

I've updated the PR tittle as per [coding convention](https://github.com/bpg/terraform-provider-proxmox/blob/main/CONTRIBUTING.md#coding-conventions), but could you please also sign-off the commit?
Thanks!

**Comment by zmingxie** [comment]
> Hi @zmingxie! 👋🏼 Thank you for the the fix!
> 
> I've updated the PR tittle as per [coding convention](https://github.com/bpg/terraform-provider-proxmox/blob/main/CONTRIBUTING.md#coding-conventions), but could you please also sign-off the commit? Thanks!

Updated. (I was just lazy 🙃 )

**Review by bpg — APPROVED** [review]
LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @zmingxie for code

**Pull request merged**
