### PR TITLE
feat: add min-tls option to provider config

### PR DESCRIPTION
**Pull request by xoxys**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/bpg/terraform-provider-proxmox/issues/930

### CODE REVIEW

**Comment by xoxys** [comment]
Need to create a test setup to test the change.

**Comment by xoxys** [comment]
Test results:

1) `min_tls` version not specified (using the provider default):

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: failed to get resources list of type ("vm") for cluster: failed to perform HTTP GET request (path: cluster/resources?type=vm) - Reason: Get "https://vm.example.com/api2/json/cluster/resources?type=vm": remote error: tls: handshake failure
│ 
│   with module.pve_server.proxmox_virtual_environment_vm.server["devcon"],
│   on .terraform/modules/pve_server/main.tf line 1, in resource "proxmox_virtual_environment_vm" "server":
│    1: resource "proxmox_virtual_environment_vm" "server" {
│ 
╵
```

2) `min_tls` version set to unsupported value:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Unable to create Proxmox VE API connection
│ 
│   with provider["registry.terraform.io/bpg/proxmox"],
│   on provider.tf line 5, in provider "proxmox":
│    5: provider "proxmox" {
│ 
│ unsupported minimal TLS version 1.4, must be one of: , 1.0, 1.1, 1.2, 1.3
╵
```

3) `min_tls` version set to `min_tls   = "1.2"`:

```
Plan: 0 to add, 1 to change, 0 to destroy.
module.pve_server.proxmox_virtual_environment_vm.server["devcon"]: Modifying... [id=306]
module.pve_server.proxmox_virtual_environment_vm.server["devcon"]: Modifications complete after 0s [id=306]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Review by bpg — APPROVED** [review]
Thanks a lot for taking care of this @xoxys! ❤️ 

I've just fixed a few minor issues and updated docs for the file resource.

LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @xoxys for code, ideas

**Pull request merged**
